name: nutrifit_mobile
description: Nutrifit Flutter app (skeleton + docs)
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  graphql_flutter: ^5.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
