# Archived deprecated workflow (version check moved into release.yml)
name: archived-deprecated-backend-version-verify
on:
  workflow_dispatch: {}
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Archived deprecated workflow. No action.'
