# Archived deprecated workflow (see release.yml)
name: archived-deprecated-backend-github-release
on:
  workflow_dispatch: {}
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Archived deprecated workflow. No action.'
