name: backend-ci

on:
  push:
    paths:
      - 'backend/**'
      - 'CHANGELOG.md'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  preflight:
    name: Backend full preflight (format/lint/tests/schema + commitlint + markdown)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Setup Node 20 (commitlint/markdownlint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install optional Node deps (if package.json exists)
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Sync deps (backend)
        working-directory: backend
        run: uv sync --all-extras --dev
      - name: Run preflight (strict md)
        working-directory: backend
        env:
          NO_COLOR: "1"
          MD_MODE: git
          MD_STRICT: "1"
        run: ./make.sh preflight
      - name: Upload preflight summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-preflight-summary
          path: backend/logs/preflight_summary.log
      - name: Upload markdownlint log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: markdownlint-log
          path: backend/logs/md_lint_latest.log
      - name: Export schema artifact
        if: always()
        working-directory: backend
        run: |
          uv run python scripts/export_schema.py --out schema_export.graphql || true
      - name: Upload schema export
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-schema
          path: backend/schema_export.graphql

  docker-integration:
    name: Docker build & integration tests
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker Build (validation)
        run: docker build --build-arg VERSION=$(grep -m1 '^version' backend/pyproject.toml | sed -E 's/^[^0-9]*([0-9]+\.[0-9]+\.[0-9]+).*/\1/') -t nutrifit-backend:ci backend
      - name: Run container
        run: |
          docker run -d --rm -p 8080:8080 --name nutrifit-backend-ci nutrifit-backend:ci
          sleep 5
      - name: Integration test (health/version/graphql)
        working-directory: backend
        run: bash scripts/integration_test.sh
      - name: Stop container
        if: always()
        run: docker stop nutrifit-backend-ci || true

  maintenance:
    name: Maintenance (changelog + badges)
    needs: docker-integration
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Sync deps
        working-directory: backend
        run: uv sync --all-extras --dev
      - name: Generate changelog (auto)
        working-directory: backend
        run: |
          ./make.sh changelog || echo "Changelog generation failed (non-blocking)"
      - name: Schema drift & badge
        working-directory: backend
        run: |
          if ./make.sh schema-check; then STATUS=synced; else STATUS=drift; fi
          cd ..
          COLOR=lightgrey; if [ "$STATUS" = "synced" ]; then COLOR=brightgreen; else COLOR=orange; fi
          sed -i "s|schema_status-[a-zA-Z0-9_-]*-[a-zA-Z]*|schema_status-${STATUS}-${COLOR}|" README.md || true
      - name: Version badge
        run: |
          version=$(grep -m1 '^version' backend/pyproject.toml | sed -E 's/^[^=]+= *"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          sed -i "s|backend_version-[a-zA-Z0-9_.-]*-green|backend_version-${version}-green|" README.md || true
          sed -i "s|backend_version-loading-grey|backend_version-${version}-green|" README.md || true
      - name: Sync textual backend release line
        run: |
          version=$(grep -m1 '^version' backend/pyproject.toml | sed -E 's/^[^=]+= *"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          if grep -q 'Release corrente backend:' README.md; then
            sed -i "s/Release corrente backend: \`v[0-9]\+\.[0-9]\+\.[0-9]\+\`/Release corrente backend: \`v${version}\`/" README.md || true
          fi
      - name: Commit aggregated maintenance changes
        run: |
          if git diff --quiet -- README.md CHANGELOG.md; then
            echo "No maintenance changes"
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          MSG="chore(maintenance): update changelog + badges + version line"
          git add README.md CHANGELOG.md || true
          git commit -m "$MSG" || exit 0
          git push

# NOTE:
# - Workflow unificato: questo file esegue preflight completo + docker + maintenance.
# - Rimuovere backend-preflight.yml (legacy) per evitare run duplicate.
