name: backend-preflight

on:
	pull_request:
		paths:
			- 'backend/**'
			- '.github/workflows/backend-preflight.yml'

jobs:
	preflight:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4
			- name: Echo placeholder
				run: |
					echo "TODO: aggiungere security scans / license checks / bandit / trivy"
