# DEPRECATED: Changelog generation merged into backend-ci maintenance job.
name: deprecated-backend-changelog
on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deprecated workflow. Use backend-ci.yml (maintenance job) instead.'
