name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Verify backend version matches tag
        id: verify
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          PY_VERSION=$(awk -F '"' '/^version[[:space:]]*=/{print $2}' backend/pyproject.toml)
          echo "Tag: $TAG"; echo "Expected version: $VERSION"; echo "Backend pyproject: $PY_VERSION"
          if [ "$PY_VERSION" != "$VERSION" ]; then
            echo "Mismatch: backend version ($PY_VERSION) != tag version ($VERSION)" >&2
            exit 1
          fi
          echo "Version match OK"

      - name: Generate Release Notes
        id: notes
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          awk '/^## \[/,/^## \[/{print}' CHANGELOG.md | sed '1d' | sed '/^## \[/q' >> $GITHUB_OUTPUT || true
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.notes.outputs.tag }}
          name: ${{ steps.notes.outputs.tag }}
          body: ${{ steps.notes.outputs.notes }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
